### ISSUE TITLE
data, domain 모듈 만들기

### ISSUE THREAD

**Issue by BeokBeok** [ParkChan/CleanArchitureStudy#1]
### 요구 사항
- 순수 코틀린 모듈인 domain 모듈을 만든다.
- 순수 코틀린 모듈인 data 모듈을 만든다.
- data 모듈은 domain 모듈을 implementation 해야 한다.
- app 모듈은 data, domain 모듈을 implementation 해야 한다.

### Flow
![image](https://user-images.githubusercontent.com/48344355/135714863-631606bc-d918-4e09-8c1e-aa840edb31a3.png)

**Comment by ParkChan** [comment]
data 모듈은 domain 모듈을 implementation 해야 한다.
👉 domain 모듈은 data모듈을 implementation 해야 한다. 가 맞아보이는데 확인부탁드릴게요~!

**Comment by BeokBeok** [comment]
>  domain 모듈은 data모듈을 implementation 해야 한다. 가 맞아보이는데 확인부탁드릴게요~!

이렇게 생각하신 이유가 무엇인가요?

data 모듈이 domain 모듈을 implementation 해야 하는 것이 맞습니다 😄

**Comment by ParkChan** [comment]
이렇게 생각하게 된 종속관계를 아래와 같이 생각하게 되면서 나온 질문이었습니다.
Presentation Layer > Domain Layer > Data Layer

1.implementation 이 android 프로젝트 내 build.gradle > dependencies {...} 내의 종속성을 의미하는것으로 이해하고 있습니다.
2.data 모듈에서 domain(Use Case)를 구현하기때문에 data 모듈이 domain 모듈을 implementation 하는것이지요?

**Comment by BeokBeok** [comment]
```
Presentation Layer > Domain Layer < Data Layer
```
위와 같은 의존성 관계가 되어야 합니다.

> 1.implementation 이 android 프로젝트 내 build.gradle > dependencies {...} 내의 종속성을 의미하는것으로 이해하고 있습니다.

맞습니다

> 2.data 모듈에서 domain(Use Case)를 구현하기때문에 data 모듈이 domain 모듈을 implementation 하는것이지요?

UseCase는 domain 모듈에서 구현해야합니다.
만약 domain 모듈이 data 모듈을 implementation 하게 된다면, domain 모듈에서는 굳이 알 필요 없는 data 모듈의 구현체까지 전부 알게 됩니다.
domain 모듈이 data 모듈의 구현체를 알 경우, domain 모듈 빌드 시 data 모듈도 같이 빌드가 진행됩니다.
각 모듈간에는 서로 구현체를 모르는 것이 좋습니다.
ref. https://proandroiddev.com/compile-less-with-solid-bd0633c1f84

@ParkChan 
domain 모듈이 data 모듈을 알 경우 -> domain 모듈이 data 모듈의 구현체를 알 경우
^ 수정했습니다

**Comment by ParkChan** [comment]
의견 감사합니다. 모르고 있던 부분이었는데 이해에 도움이 되었습니다🤞

**Comment by ParkChan** [comment]
등록하여주신 요구사항대로 프로젝트를 구성하였습니다.
