### ISSUE TITLE
HTTP 연동

### ISSUE THREAD

**Issue by BeokBeok** [ParkChan/CleanArchitureStudy#3]
#### 네이버 API를 사용해서 영화 정보를 가져와야 합니다
- GET, v1/search/movie.json

### 프로그래밍 요구 사항
1. 영화 정보를 가져오는 API는 data 모듈에 구현되어야 합니다
2. data 모듈의 구현체는 모두 internal 키워드가 붙어야 합니다

**Comment by ParkChan** [comment]
e5cb98fd99088cd59cda3748d4bbc565fa69bda8 Data 모듈을 구현 하였습니다.
